// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAmg9vXBccBzmMNOxQid6PMrgzvuDZhrHk',
    appId: '1:522835482262:web:c8fa0636ddec0dcc7454b7',
    messagingSenderId: '522835482262',
    projectId: 'todo-app-27454',
    authDomain: 'todo-app-27454.firebaseapp.com',
    storageBucket: 'todo-app-27454.firebasestorage.app',
    measurementId: 'G-0VEWG0HFZS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBT-s7C4hWpz7idCkMarf3cVAZpVBSgS8s',
    appId: '1:522835482262:android:549325e8f88b40e27454b7',
    messagingSenderId: '522835482262',
    projectId: 'todo-app-27454',
    storageBucket: 'todo-app-27454.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDfEvKC9BAKHCl6VYrOXx2cnV-JYTFenug',
    appId: '1:522835482262:ios:bb626167bf91638d7454b7',
    messagingSenderId: '522835482262',
    projectId: 'todo-app-27454',
    storageBucket: 'todo-app-27454.firebasestorage.app',
    iosBundleId: 'com.example.todoApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDfEvKC9BAKHCl6VYrOXx2cnV-JYTFenug',
    appId: '1:522835482262:ios:bb626167bf91638d7454b7',
    messagingSenderId: '522835482262',
    projectId: 'todo-app-27454',
    storageBucket: 'todo-app-27454.firebasestorage.app',
    iosBundleId: 'com.example.todoApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAmg9vXBccBzmMNOxQid6PMrgzvuDZhrHk',
    appId: '1:522835482262:web:121efa0abe11a0b97454b7',
    messagingSenderId: '522835482262',
    projectId: 'todo-app-27454',
    authDomain: 'todo-app-27454.firebaseapp.com',
    storageBucket: 'todo-app-27454.firebasestorage.app',
    measurementId: 'G-BDK4X7WY65',
  );
}
